# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 20 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: dbyll
google_analytics: dbyll
title: dbyll

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: hibbisoft

description: Ramblings about software development and such
author:
  name: Sebastian Johansson
  email: sebastian.johansson@hibbisoft.se
  github: https://github.com/sebbebebbe
  twitter: https://twitter.com/sebbe_bebbe
  linkedin: http://www.linkedin.com/in/sebastian-johansson
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate
